# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/cybex8

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/cybex8

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/cybex8/CMakeFiles /root/cybex8/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/cybex8/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project_secp256k1

# Build rule for target.
project_secp256k1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project_secp256k1
.PHONY : project_secp256k1

# fast build rule for target.
project_secp256k1/fast:
	$(MAKE) -f libraries/fc/CMakeFiles/project_secp256k1.dir/build.make libraries/fc/CMakeFiles/project_secp256k1.dir/build
.PHONY : project_secp256k1/fast

#=============================================================================
# Target rules for targets named fc

# Build rule for target.
fc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc
.PHONY : fc

# fast build rule for target.
fc/fast:
	$(MAKE) -f libraries/fc/CMakeFiles/fc.dir/build.make libraries/fc/CMakeFiles/fc.dir/build
.PHONY : fc/fast

#=============================================================================
# Target rules for targets named all_tests

# Build rule for target.
all_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all_tests
.PHONY : all_tests

# fast build rule for target.
all_tests/fast:
	$(MAKE) -f libraries/fc/tests/CMakeFiles/all_tests.dir/build.make libraries/fc/tests/CMakeFiles/all_tests.dir/build
.PHONY : all_tests/fast

#=============================================================================
# Target rules for targets named task_cancel_test

# Build rule for target.
task_cancel_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 task_cancel_test
.PHONY : task_cancel_test

# fast build rule for target.
task_cancel_test/fast:
	$(MAKE) -f libraries/fc/tests/CMakeFiles/task_cancel_test.dir/build.make libraries/fc/tests/CMakeFiles/task_cancel_test.dir/build
.PHONY : task_cancel_test/fast

#=============================================================================
# Target rules for targets named blind

# Build rule for target.
blind: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blind
.PHONY : blind

# fast build rule for target.
blind/fast:
	$(MAKE) -f libraries/fc/tests/CMakeFiles/blind.dir/build.make libraries/fc/tests/CMakeFiles/blind.dir/build
.PHONY : blind/fast

#=============================================================================
# Target rules for targets named api

# Build rule for target.
api: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 api
.PHONY : api

# fast build rule for target.
api/fast:
	$(MAKE) -f libraries/fc/tests/CMakeFiles/api.dir/build.make libraries/fc/tests/CMakeFiles/api.dir/build
.PHONY : api/fast

#=============================================================================
# Target rules for targets named hmac_test

# Build rule for target.
hmac_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hmac_test
.PHONY : hmac_test

# fast build rule for target.
hmac_test/fast:
	$(MAKE) -f libraries/fc/tests/CMakeFiles/hmac_test.dir/build.make libraries/fc/tests/CMakeFiles/hmac_test.dir/build
.PHONY : hmac_test/fast

#=============================================================================
# Target rules for targets named bloom_test

# Build rule for target.
bloom_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bloom_test
.PHONY : bloom_test

# fast build rule for target.
bloom_test/fast:
	$(MAKE) -f libraries/fc/tests/CMakeFiles/bloom_test.dir/build.make libraries/fc/tests/CMakeFiles/bloom_test.dir/build
.PHONY : bloom_test/fast

#=============================================================================
# Target rules for targets named real128_test

# Build rule for target.
real128_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 real128_test
.PHONY : real128_test

# fast build rule for target.
real128_test/fast:
	$(MAKE) -f libraries/fc/tests/CMakeFiles/real128_test.dir/build.make libraries/fc/tests/CMakeFiles/real128_test.dir/build
.PHONY : real128_test/fast

#=============================================================================
# Target rules for targets named log_test

# Build rule for target.
log_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 log_test
.PHONY : log_test

# fast build rule for target.
log_test/fast:
	$(MAKE) -f libraries/fc/tests/CMakeFiles/log_test.dir/build.make libraries/fc/tests/CMakeFiles/log_test.dir/build
.PHONY : log_test/fast

#=============================================================================
# Target rules for targets named blinding_test

# Build rule for target.
blinding_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blinding_test
.PHONY : blinding_test

# fast build rule for target.
blinding_test/fast:
	$(MAKE) -f libraries/fc/tests/CMakeFiles/blinding_test.dir/build.make libraries/fc/tests/CMakeFiles/blinding_test.dir/build
.PHONY : blinding_test/fast

#=============================================================================
# Target rules for targets named bip_lock

# Build rule for target.
bip_lock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bip_lock
.PHONY : bip_lock

# fast build rule for target.
bip_lock/fast:
	$(MAKE) -f libraries/fc/tests/CMakeFiles/bip_lock.dir/build.make libraries/fc/tests/CMakeFiles/bip_lock.dir/build
.PHONY : bip_lock/fast

#=============================================================================
# Target rules for targets named ecc_test

# Build rule for target.
ecc_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ecc_test
.PHONY : ecc_test

# fast build rule for target.
ecc_test/fast:
	$(MAKE) -f libraries/fc/tests/CMakeFiles/ecc_test.dir/build.make libraries/fc/tests/CMakeFiles/ecc_test.dir/build
.PHONY : ecc_test/fast

#=============================================================================
# Target rules for targets named graphene_db

# Build rule for target.
graphene_db: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphene_db
.PHONY : graphene_db

# fast build rule for target.
graphene_db/fast:
	$(MAKE) -f libraries/db/CMakeFiles/graphene_db.dir/build.make libraries/db/CMakeFiles/graphene_db.dir/build
.PHONY : graphene_db/fast

#=============================================================================
# Target rules for targets named deterministic_openssl_rand

# Build rule for target.
deterministic_openssl_rand: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deterministic_openssl_rand
.PHONY : deterministic_openssl_rand

# fast build rule for target.
deterministic_openssl_rand/fast:
	$(MAKE) -f libraries/deterministic_openssl_rand/CMakeFiles/deterministic_openssl_rand.dir/build.make libraries/deterministic_openssl_rand/CMakeFiles/deterministic_openssl_rand.dir/build
.PHONY : deterministic_openssl_rand/fast

#=============================================================================
# Target rules for targets named build_hardfork_hpp

# Build rule for target.
build_hardfork_hpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build_hardfork_hpp
.PHONY : build_hardfork_hpp

# fast build rule for target.
build_hardfork_hpp/fast:
	$(MAKE) -f libraries/chain/CMakeFiles/build_hardfork_hpp.dir/build.make libraries/chain/CMakeFiles/build_hardfork_hpp.dir/build
.PHONY : build_hardfork_hpp/fast

#=============================================================================
# Target rules for targets named graphene_chain

# Build rule for target.
graphene_chain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphene_chain
.PHONY : graphene_chain

# fast build rule for target.
graphene_chain/fast:
	$(MAKE) -f libraries/chain/CMakeFiles/graphene_chain.dir/build.make libraries/chain/CMakeFiles/graphene_chain.dir/build
.PHONY : graphene_chain/fast

#=============================================================================
# Target rules for targets named graphene_egenesis_none

# Build rule for target.
graphene_egenesis_none: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphene_egenesis_none
.PHONY : graphene_egenesis_none

# fast build rule for target.
graphene_egenesis_none/fast:
	$(MAKE) -f libraries/egenesis/CMakeFiles/graphene_egenesis_none.dir/build.make libraries/egenesis/CMakeFiles/graphene_egenesis_none.dir/build
.PHONY : graphene_egenesis_none/fast

#=============================================================================
# Target rules for targets named graphene_egenesis_full

# Build rule for target.
graphene_egenesis_full: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphene_egenesis_full
.PHONY : graphene_egenesis_full

# fast build rule for target.
graphene_egenesis_full/fast:
	$(MAKE) -f libraries/egenesis/CMakeFiles/graphene_egenesis_full.dir/build.make libraries/egenesis/CMakeFiles/graphene_egenesis_full.dir/build
.PHONY : graphene_egenesis_full/fast

#=============================================================================
# Target rules for targets named embed_genesis

# Build rule for target.
embed_genesis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 embed_genesis
.PHONY : embed_genesis

# fast build rule for target.
embed_genesis/fast:
	$(MAKE) -f libraries/egenesis/CMakeFiles/embed_genesis.dir/build.make libraries/egenesis/CMakeFiles/embed_genesis.dir/build
.PHONY : embed_genesis/fast

#=============================================================================
# Target rules for targets named graphene_egenesis_brief

# Build rule for target.
graphene_egenesis_brief: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphene_egenesis_brief
.PHONY : graphene_egenesis_brief

# fast build rule for target.
graphene_egenesis_brief/fast:
	$(MAKE) -f libraries/egenesis/CMakeFiles/graphene_egenesis_brief.dir/build.make libraries/egenesis/CMakeFiles/graphene_egenesis_brief.dir/build
.PHONY : graphene_egenesis_brief/fast

#=============================================================================
# Target rules for targets named graphene_net

# Build rule for target.
graphene_net: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphene_net
.PHONY : graphene_net

# fast build rule for target.
graphene_net/fast:
	$(MAKE) -f libraries/net/CMakeFiles/graphene_net.dir/build.make libraries/net/CMakeFiles/graphene_net.dir/build
.PHONY : graphene_net/fast

#=============================================================================
# Target rules for targets named graphene_utilities

# Build rule for target.
graphene_utilities: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphene_utilities
.PHONY : graphene_utilities

# fast build rule for target.
graphene_utilities/fast:
	$(MAKE) -f libraries/utilities/CMakeFiles/graphene_utilities.dir/build.make libraries/utilities/CMakeFiles/graphene_utilities.dir/build
.PHONY : graphene_utilities/fast

#=============================================================================
# Target rules for targets named graphene_app

# Build rule for target.
graphene_app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphene_app
.PHONY : graphene_app

# fast build rule for target.
graphene_app/fast:
	$(MAKE) -f libraries/app/CMakeFiles/graphene_app.dir/build.make libraries/app/CMakeFiles/graphene_app.dir/build
.PHONY : graphene_app/fast

#=============================================================================
# Target rules for targets named graphene_witness

# Build rule for target.
graphene_witness: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphene_witness
.PHONY : graphene_witness

# fast build rule for target.
graphene_witness/fast:
	$(MAKE) -f libraries/plugins/witness/CMakeFiles/graphene_witness.dir/build.make libraries/plugins/witness/CMakeFiles/graphene_witness.dir/build
.PHONY : graphene_witness/fast

#=============================================================================
# Target rules for targets named graphene_account_history

# Build rule for target.
graphene_account_history: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphene_account_history
.PHONY : graphene_account_history

# fast build rule for target.
graphene_account_history/fast:
	$(MAKE) -f libraries/plugins/account_history/CMakeFiles/graphene_account_history.dir/build.make libraries/plugins/account_history/CMakeFiles/graphene_account_history.dir/build
.PHONY : graphene_account_history/fast

#=============================================================================
# Target rules for targets named graphene_market_history

# Build rule for target.
graphene_market_history: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphene_market_history
.PHONY : graphene_market_history

# fast build rule for target.
graphene_market_history/fast:
	$(MAKE) -f libraries/plugins/market_history/CMakeFiles/graphene_market_history.dir/build.make libraries/plugins/market_history/CMakeFiles/graphene_market_history.dir/build
.PHONY : graphene_market_history/fast

#=============================================================================
# Target rules for targets named graphene_delayed_node

# Build rule for target.
graphene_delayed_node: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphene_delayed_node
.PHONY : graphene_delayed_node

# fast build rule for target.
graphene_delayed_node/fast:
	$(MAKE) -f libraries/plugins/delayed_node/CMakeFiles/graphene_delayed_node.dir/build.make libraries/plugins/delayed_node/CMakeFiles/graphene_delayed_node.dir/build
.PHONY : graphene_delayed_node/fast

#=============================================================================
# Target rules for targets named graphene_debug_witness

# Build rule for target.
graphene_debug_witness: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphene_debug_witness
.PHONY : graphene_debug_witness

# fast build rule for target.
graphene_debug_witness/fast:
	$(MAKE) -f libraries/plugins/debug_witness/CMakeFiles/graphene_debug_witness.dir/build.make libraries/plugins/debug_witness/CMakeFiles/graphene_debug_witness.dir/build
.PHONY : graphene_debug_witness/fast

#=============================================================================
# Target rules for targets named graphene_wallet

# Build rule for target.
graphene_wallet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphene_wallet
.PHONY : graphene_wallet

# fast build rule for target.
graphene_wallet/fast:
	$(MAKE) -f libraries/wallet/CMakeFiles/graphene_wallet.dir/build.make libraries/wallet/CMakeFiles/graphene_wallet.dir/build
.PHONY : graphene_wallet/fast

#=============================================================================
# Target rules for targets named cat-parts

# Build rule for target.
cat-parts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cat-parts
.PHONY : cat-parts

# fast build rule for target.
cat-parts/fast:
	$(MAKE) -f programs/build_helpers/CMakeFiles/cat-parts.dir/build.make programs/build_helpers/CMakeFiles/cat-parts.dir/build
.PHONY : cat-parts/fast

#=============================================================================
# Target rules for targets named member_enumerator

# Build rule for target.
member_enumerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 member_enumerator
.PHONY : member_enumerator

# fast build rule for target.
member_enumerator/fast:
	$(MAKE) -f programs/build_helpers/CMakeFiles/member_enumerator.dir/build.make programs/build_helpers/CMakeFiles/member_enumerator.dir/build
.PHONY : member_enumerator/fast

#=============================================================================
# Target rules for targets named cli_wallet

# Build rule for target.
cli_wallet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cli_wallet
.PHONY : cli_wallet

# fast build rule for target.
cli_wallet/fast:
	$(MAKE) -f programs/cli_wallet/CMakeFiles/cli_wallet.dir/build.make programs/cli_wallet/CMakeFiles/cli_wallet.dir/build
.PHONY : cli_wallet/fast

#=============================================================================
# Target rules for targets named genesis_update

# Build rule for target.
genesis_update: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 genesis_update
.PHONY : genesis_update

# fast build rule for target.
genesis_update/fast:
	$(MAKE) -f programs/genesis_util/CMakeFiles/genesis_update.dir/build.make programs/genesis_util/CMakeFiles/genesis_update.dir/build
.PHONY : genesis_update/fast

#=============================================================================
# Target rules for targets named get_dev_key

# Build rule for target.
get_dev_key: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_dev_key
.PHONY : get_dev_key

# fast build rule for target.
get_dev_key/fast:
	$(MAKE) -f programs/genesis_util/CMakeFiles/get_dev_key.dir/build.make programs/genesis_util/CMakeFiles/get_dev_key.dir/build
.PHONY : get_dev_key/fast

#=============================================================================
# Target rules for targets named convert_address

# Build rule for target.
convert_address: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convert_address
.PHONY : convert_address

# fast build rule for target.
convert_address/fast:
	$(MAKE) -f programs/genesis_util/CMakeFiles/convert_address.dir/build.make programs/genesis_util/CMakeFiles/convert_address.dir/build
.PHONY : convert_address/fast

#=============================================================================
# Target rules for targets named witness_node

# Build rule for target.
witness_node: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 witness_node
.PHONY : witness_node

# fast build rule for target.
witness_node/fast:
	$(MAKE) -f programs/witness_node/CMakeFiles/witness_node.dir/build.make programs/witness_node/CMakeFiles/witness_node.dir/build
.PHONY : witness_node/fast

#=============================================================================
# Target rules for targets named debug_node

# Build rule for target.
debug_node: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug_node
.PHONY : debug_node

# fast build rule for target.
debug_node/fast:
	$(MAKE) -f programs/debug_node/CMakeFiles/debug_node.dir/build.make programs/debug_node/CMakeFiles/debug_node.dir/build
.PHONY : debug_node/fast

#=============================================================================
# Target rules for targets named delayed_node

# Build rule for target.
delayed_node: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 delayed_node
.PHONY : delayed_node

# fast build rule for target.
delayed_node/fast:
	$(MAKE) -f programs/delayed_node/CMakeFiles/delayed_node.dir/build.make programs/delayed_node/CMakeFiles/delayed_node.dir/build
.PHONY : delayed_node/fast

#=============================================================================
# Target rules for targets named js_operation_serializer

# Build rule for target.
js_operation_serializer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 js_operation_serializer
.PHONY : js_operation_serializer

# fast build rule for target.
js_operation_serializer/fast:
	$(MAKE) -f programs/js_operation_serializer/CMakeFiles/js_operation_serializer.dir/build.make programs/js_operation_serializer/CMakeFiles/js_operation_serializer.dir/build
.PHONY : js_operation_serializer/fast

#=============================================================================
# Target rules for targets named size_checker

# Build rule for target.
size_checker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 size_checker
.PHONY : size_checker

# fast build rule for target.
size_checker/fast:
	$(MAKE) -f programs/size_checker/CMakeFiles/size_checker.dir/build.make programs/size_checker/CMakeFiles/size_checker.dir/build
.PHONY : size_checker/fast

#=============================================================================
# Target rules for targets named app_test

# Build rule for target.
app_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app_test
.PHONY : app_test

# fast build rule for target.
app_test/fast:
	$(MAKE) -f tests/CMakeFiles/app_test.dir/build.make tests/CMakeFiles/app_test.dir/build
.PHONY : app_test/fast

#=============================================================================
# Target rules for targets named performance_test

# Build rule for target.
performance_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 performance_test
.PHONY : performance_test

# fast build rule for target.
performance_test/fast:
	$(MAKE) -f tests/CMakeFiles/performance_test.dir/build.make tests/CMakeFiles/performance_test.dir/build
.PHONY : performance_test/fast

#=============================================================================
# Target rules for targets named chain_bench

# Build rule for target.
chain_bench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chain_bench
.PHONY : chain_bench

# fast build rule for target.
chain_bench/fast:
	$(MAKE) -f tests/CMakeFiles/chain_bench.dir/build.make tests/CMakeFiles/chain_bench.dir/build
.PHONY : chain_bench/fast

#=============================================================================
# Target rules for targets named chain_test

# Build rule for target.
chain_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chain_test
.PHONY : chain_test

# fast build rule for target.
chain_test/fast:
	$(MAKE) -f tests/CMakeFiles/chain_test.dir/build.make tests/CMakeFiles/chain_test.dir/build
.PHONY : chain_test/fast

#=============================================================================
# Target rules for targets named intense_test

# Build rule for target.
intense_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 intense_test
.PHONY : intense_test

# fast build rule for target.
intense_test/fast:
	$(MAKE) -f tests/CMakeFiles/intense_test.dir/build.make tests/CMakeFiles/intense_test.dir/build
.PHONY : intense_test/fast

#=============================================================================
# Target rules for targets named generate_empty_blocks

# Build rule for target.
generate_empty_blocks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate_empty_blocks
.PHONY : generate_empty_blocks

# fast build rule for target.
generate_empty_blocks/fast:
	$(MAKE) -f tests/generate_empty_blocks/CMakeFiles/generate_empty_blocks.dir/build.make tests/generate_empty_blocks/CMakeFiles/generate_empty_blocks.dir/build
.PHONY : generate_empty_blocks/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... project_secp256k1"
	@echo "... fc"
	@echo "... all_tests"
	@echo "... task_cancel_test"
	@echo "... blind"
	@echo "... api"
	@echo "... hmac_test"
	@echo "... bloom_test"
	@echo "... real128_test"
	@echo "... log_test"
	@echo "... blinding_test"
	@echo "... bip_lock"
	@echo "... ecc_test"
	@echo "... graphene_db"
	@echo "... deterministic_openssl_rand"
	@echo "... build_hardfork_hpp"
	@echo "... graphene_chain"
	@echo "... graphene_egenesis_none"
	@echo "... graphene_egenesis_full"
	@echo "... embed_genesis"
	@echo "... graphene_egenesis_brief"
	@echo "... graphene_net"
	@echo "... graphene_utilities"
	@echo "... graphene_app"
	@echo "... graphene_witness"
	@echo "... graphene_account_history"
	@echo "... graphene_market_history"
	@echo "... graphene_delayed_node"
	@echo "... graphene_debug_witness"
	@echo "... graphene_wallet"
	@echo "... cat-parts"
	@echo "... member_enumerator"
	@echo "... cli_wallet"
	@echo "... genesis_update"
	@echo "... get_dev_key"
	@echo "... convert_address"
	@echo "... witness_node"
	@echo "... debug_node"
	@echo "... delayed_node"
	@echo "... js_operation_serializer"
	@echo "... size_checker"
	@echo "... app_test"
	@echo "... performance_test"
	@echo "... chain_bench"
	@echo "... chain_test"
	@echo "... intense_test"
	@echo "... generate_empty_blocks"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

